//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPanel_UI.LoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServiceReference.LoginServiceSoap")]
    public interface LoginServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        LoginPanel_UI.LoginServiceReference.SignInResponse SignIn(LoginPanel_UI.LoginServiceReference.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<LoginPanel_UI.LoginServiceReference.SignInResponse> SignInAsync(LoginPanel_UI.LoginServiceReference.SignInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public LoginPanel_UI.LoginServiceReference.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(LoginPanel_UI.LoginServiceReference.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public LoginPanel_UI.LoginServiceReference.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(LoginPanel_UI.LoginServiceReference.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignInResult;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(string SignInResult) {
            this.SignInResult = SignInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceSoapChannel : LoginPanel_UI.LoginServiceReference.LoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceSoapClient : System.ServiceModel.ClientBase<LoginPanel_UI.LoginServiceReference.LoginServiceSoap>, LoginPanel_UI.LoginServiceReference.LoginServiceSoap {
        
        public LoginServiceSoapClient() {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LoginPanel_UI.LoginServiceReference.SignInResponse LoginPanel_UI.LoginServiceReference.LoginServiceSoap.SignIn(LoginPanel_UI.LoginServiceReference.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public string SignIn(string username, string password) {
            LoginPanel_UI.LoginServiceReference.SignInRequest inValue = new LoginPanel_UI.LoginServiceReference.SignInRequest();
            inValue.Body = new LoginPanel_UI.LoginServiceReference.SignInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            LoginPanel_UI.LoginServiceReference.SignInResponse retVal = ((LoginPanel_UI.LoginServiceReference.LoginServiceSoap)(this)).SignIn(inValue);
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginPanel_UI.LoginServiceReference.SignInResponse> LoginPanel_UI.LoginServiceReference.LoginServiceSoap.SignInAsync(LoginPanel_UI.LoginServiceReference.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginPanel_UI.LoginServiceReference.SignInResponse> SignInAsync(string username, string password) {
            LoginPanel_UI.LoginServiceReference.SignInRequest inValue = new LoginPanel_UI.LoginServiceReference.SignInRequest();
            inValue.Body = new LoginPanel_UI.LoginServiceReference.SignInRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((LoginPanel_UI.LoginServiceReference.LoginServiceSoap)(this)).SignInAsync(inValue);
        }
    }
}
